package com.cit.robot;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSlider;
import javax.swing.JTextField;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author cit3d11
 */
public class M extends JFrame implements ActionListener {

	/**
	 * Creates new form M
	 */

	// Variables declaration
	private JButton Button_closeport;
	private JButton Button_openport;
	private JButton Button_send;
	private JCheckBox Checkbox_serv1;
	private JCheckBox Checkbox_serv10;
	private JCheckBox Checkbox_serv11;
	private JCheckBox Checkbox_serv12;
	private JCheckBox Checkbox_serv13;
	private JCheckBox Checkbox_serv14;
	private JCheckBox Checkbox_serv15;
	private JCheckBox Checkbox_serv16;
	private JCheckBox Checkbox_serv17;
	private JCheckBox Checkbox_serv2;
	private JCheckBox Checkbox_serv3;
	private JCheckBox Checkbox_serv4;
	private JCheckBox Checkbox_serv5;
	private JCheckBox Checkbox_serv6;
	private JCheckBox Checkbox_serv7;
	private JCheckBox Checkbox_serv8;
	private JCheckBox Checkbox_serv9;
	private JComboBox Comobox_boudrate;
	private JComboBox Comobox_datebits;
	private JComboBox Comobox_paritybits;
	private JComboBox Comobox_port;
	private JComboBox Comobox_stopbits;
	private JLabel Lable_baudrate;
	private JLabel Lable_databits;
	private JLabel Lable_paritybits;
	private JLabel Lable_port;
	private JLabel Lable_stopbits;
	private JSlider Slider_serv1;
	private JSlider Slider_serv10;
	private JSlider Slider_serv11;
	private JSlider Slider_serv12;
	private JSlider Slider_serv13;
	private JSlider Slider_serv14;
	private JSlider Slider_serv15;
	private JSlider Slider_serv16;
	private JSlider Slider_serv17;
	private JSlider Slider_serv2;
	private JSlider Slider_serv3;
	private JSlider Slider_serv4;
	private JSlider Slider_serv5;
	private JSlider Slider_serv6;
	private JSlider Slider_serv7;
	private JSlider Slider_serv8;
	private JSlider Slider_serv9;
	private JTextField Textfiled_serv1;
	private JTextField Textfiled_serv10;
	private JTextField Textfiled_serv11;
	private JTextField Textfiled_serv12;
	private JTextField Textfiled_serv13;
	private JTextField Textfiled_serv14;
	private JTextField Textfiled_serv15;
	private JTextField Textfiled_serv16;
	private JTextField Textfiled_serv17;
	private JTextField Textfiled_serv2;
	private JTextField Textfiled_serv3;
	private JTextField Textfiled_serv4;
	private JTextField Textfiled_serv5;
	private JTextField Textfiled_serv6;
	private JTextField Textfiled_serv7;
	private JTextField Textfiled_serv8;
	private JTextField Textfiled_serv9;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration

	// 为滑动条增加时间
	ChangeListener listener1;
	ChangeListener listener2;
	ChangeListener listener3;
	ChangeListener listener4;
	ChangeListener listener5;
	ChangeListener listener6;
	ChangeListener listener7;
	ChangeListener listener8;
	ChangeListener listener9;
	ChangeListener listener10;
	ChangeListener listener11;
	ChangeListener listener12;
	ChangeListener listener13;
	ChangeListener listener14;
	ChangeListener listener15;
	ChangeListener listener16;
	ChangeListener listener17;

	// 定义17个字符串，用于存储每个滑动条的值；
	protected String mesg1;
	protected String mesg2;
	protected String mesg3;
	protected String mesg4;
	protected String mesg5;
	protected String mesg6;
	protected String mesg7;
	protected String mesg8;
	protected String mesg9;
	protected String mesg10;
	protected String mesg11;
	protected String mesg12;
	protected String mesg13;
	protected String mesg14;
	protected String mesg15;
	protected String mesg16;
	protected String mesg17;

	protected int sendCount;
	protected int reciveCount;

	Selfserial serial = new Selfserial();
	DealMesg dealmesg = new DealMesg();

	public M() {
		super("机器人步态规划v_1.1");
		setResizable(false);
		serial.scanPorts();
		initComponents();
		setVisible(true);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1 = new JPanel();

		Textfiled_serv1 = new JTextField("0");
		Slider_serv1 = new JSlider(-50, 50);
		Checkbox_serv1 = new JCheckBox();
		Checkbox_serv1.setText("舵机1");
		setSlider(Slider_serv1, listener1, Textfiled_serv1);

		Slider_serv2 = new JSlider(-50, 50);
		Textfiled_serv2 = new JTextField("0");
		Checkbox_serv2 = new JCheckBox();
		Checkbox_serv2.setText("舵机2");
		setSlider(Slider_serv2, listener2, Textfiled_serv2);

		Textfiled_serv3 = new JTextField("0");
		Slider_serv3 = new JSlider(-50, 50);
		Checkbox_serv3 = new JCheckBox();
		Checkbox_serv3.setText("舵机3");
		setSlider(Slider_serv3, listener3, Textfiled_serv3);

		Textfiled_serv4 = new JTextField("0");
		Slider_serv4 = new JSlider(-50, 50);
		Checkbox_serv4 = new JCheckBox();
		Checkbox_serv4.setText("舵机4");
		setSlider(Slider_serv4, listener4, Textfiled_serv4);

		Textfiled_serv5 = new JTextField("0");
		Slider_serv5 = new JSlider(-50, 50);
		Checkbox_serv5 = new JCheckBox();
		Checkbox_serv5.setText("舵机5");
		setSlider(Slider_serv5, listener5, Textfiled_serv5);

		Textfiled_serv6 = new JTextField("0");
		Slider_serv6 = new JSlider(-50, 50);
		Checkbox_serv6 = new JCheckBox();
		Checkbox_serv6.setText("舵机6");
		setSlider(Slider_serv6, listener6, Textfiled_serv6);

		Textfiled_serv7 = new JTextField("0");
		Slider_serv7 = new JSlider(-50, 50);
		Checkbox_serv7 = new JCheckBox();
		Checkbox_serv7.setText("舵机7");
		setSlider(Slider_serv7, listener7, Textfiled_serv7);

		Textfiled_serv8 = new JTextField("0");
		Slider_serv8 = new JSlider(-50, 50);
		Checkbox_serv8 = new JCheckBox();
		Checkbox_serv8.setText("舵机8");
		setSlider(Slider_serv8, listener8, Textfiled_serv8);

		Textfiled_serv9 = new JTextField("0");
		Slider_serv9 = new JSlider(-50, 50);
		Checkbox_serv9 = new JCheckBox();
		Checkbox_serv9.setText("舵机9");
		setSlider(Slider_serv9, listener9, Textfiled_serv9);

		Textfiled_serv10 = new JTextField("0");
		Slider_serv10 = new JSlider(-50, 50);
		Checkbox_serv10 = new JCheckBox();
		Checkbox_serv10.setText("舵机10");
		setSlider(Slider_serv10, listener10, Textfiled_serv10);

		Textfiled_serv11 = new JTextField("0");
		Slider_serv11 = new JSlider(-50, 50);
		Checkbox_serv11 = new JCheckBox();
		Checkbox_serv11.setText("舵机11");
		setSlider(Slider_serv11, listener11, Textfiled_serv11);

		Textfiled_serv12 = new JTextField("0");
		Slider_serv12 = new JSlider(-50, 50);
		Checkbox_serv12 = new JCheckBox();
		Checkbox_serv12.setText("舵机12");
		setSlider(Slider_serv12, listener12, Textfiled_serv12);

		Textfiled_serv13 = new JTextField("0");
		Slider_serv13 = new JSlider(-50, 50);
		Checkbox_serv13 = new JCheckBox();
		Checkbox_serv13.setText("舵机13");
		setSlider(Slider_serv13, listener13, Textfiled_serv13);

		Textfiled_serv14 = new JTextField("0");
		Slider_serv14 = new JSlider(-50, 50);
		Checkbox_serv14 = new JCheckBox();
		Checkbox_serv14.setText("舵机14");
		setSlider(Slider_serv14, listener14, Textfiled_serv14);

		Textfiled_serv15 = new JTextField("0");
		Slider_serv15 = new JSlider(-50, 50);
		Checkbox_serv15 = new JCheckBox();
		Checkbox_serv15.setText("舵机15");
		setSlider(Slider_serv15, listener15, Textfiled_serv15);

		Textfiled_serv16 = new JTextField("0");
		Slider_serv16 = new JSlider(-50, 50);
		Checkbox_serv16 = new JCheckBox();
		Checkbox_serv16.setText("舵机16");
		setSlider(Slider_serv16, listener16, Textfiled_serv16);

		Textfiled_serv17 = new JTextField("0");
		Slider_serv17 = new JSlider(-50, 50);
		Checkbox_serv17 = new JCheckBox();
		Checkbox_serv17.setText("舵机17");
		setSlider(Slider_serv17, listener17, Textfiled_serv17);

		Lable_port = new JLabel();
		Lable_port.setText("串口号");
		Comobox_port = new JComboBox<String>((String[]) serial.getportList()
				.toArray(new String[0]));
		Comobox_port.addActionListener(this);

		Lable_baudrate = new JLabel();
		Lable_baudrate.setText("波特率");
		Comobox_boudrate = new JComboBox<Integer>(new Integer[] { 2400, 4800,
				9600, 14400, 19200, 38400, 56000 });
		Comobox_boudrate.setSelectedIndex(2);
		Comobox_boudrate.addActionListener(this);

		Lable_databits = new JLabel();
		Lable_databits.setText("数据位");
		Comobox_datebits = new JComboBox<Integer>(new Integer[] { 5, 6, 7, 8,
				40 });
		Comobox_datebits.setSelectedIndex(3);
		Comobox_datebits.addActionListener(this);

		Lable_stopbits = new JLabel();
		Lable_stopbits.setText("停止位");
		Comobox_stopbits = new JComboBox<String>(
				new String[] { "1", "2", "1.5" });
		Comobox_stopbits.addActionListener(this);

		Lable_paritybits = new JLabel();
		Lable_paritybits.setText("校验位");
		Comobox_paritybits = new JComboBox<String>(new String[] { "NONE",
				"ODD", "EVEN", "MARK", "SPACE" });
		Comobox_paritybits.addActionListener(this);

		Button_openport = new JButton();
		Button_openport.setText("打开端口");
		Button_openport.addActionListener(this);

		Button_closeport = new JButton();
		Button_closeport.setText("关闭端口");
		Button_closeport.addActionListener(this);

		Button_send = new JButton();
		Button_send.setText("发送");
		Button_send.addActionListener(this);
		
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////		
/*
 * this part is created by netbeans for the frame automately, pls do not change
 * begin
 */
		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								Textfiled_serv10,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								30,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								Checkbox_serv10))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				Slider_serv10,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				89,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(266,
																												266,
																												266)
																										.addComponent(
																												Checkbox_serv8))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								jPanel1Layout
																										.createSequentialGroup()
																										.addContainerGap()
																										.addComponent(
																												Textfiled_serv8,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												30,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				Slider_serv8,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				89,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(60,
																				60,
																				60)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								Checkbox_serv9)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(21,
																												21,
																												21)
																										.addComponent(
																												Textfiled_serv9,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												30,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				Slider_serv9,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				89,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(71,
																												71,
																												71)
																										.addComponent(
																												Checkbox_serv11))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								jPanel1Layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												Textfiled_serv11,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												30,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				Slider_serv11,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				89,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(249,
																				249,
																				249)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(21,
																												21,
																												21)
																										.addComponent(
																												Textfiled_serv12,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												30,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addComponent(
																								Checkbox_serv12))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				Slider_serv12,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				89,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								Checkbox_serv13,
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								Textfiled_serv13,
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								30,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				Slider_serv13,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				89,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addGroup(
																								jPanel1Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																										.addGroup(
																												jPanel1Layout
																														.createSequentialGroup()
																														.addGap(103,
																																103,
																																103)
																														.addComponent(
																																Textfiled_serv4,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																30,
																																javax.swing.GroupLayout.PREFERRED_SIZE))
																										.addGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING,
																												jPanel1Layout
																														.createSequentialGroup()
																														.addContainerGap()
																														.addComponent(
																																Checkbox_serv4)))
																						.addGroup(
																								jPanel1Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																										.addGroup(
																												jPanel1Layout
																														.createSequentialGroup()
																														.addGap(21,
																																21,
																																21)
																														.addComponent(
																																Textfiled_serv6,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																30,
																																javax.swing.GroupLayout.PREFERRED_SIZE))
																										.addComponent(
																												Checkbox_serv6)))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								Slider_serv6,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								89,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								Slider_serv4,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								89,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				8,
																				Short.MAX_VALUE)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								Textfiled_serv2,
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								30,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								Checkbox_serv2,
																								javax.swing.GroupLayout.Alignment.TRAILING))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				Slider_serv2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				89,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(136,
																				136,
																				136)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								Textfiled_serv3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								30,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								Checkbox_serv3))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				Slider_serv3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				89,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(36,
																												36,
																												36)
																										.addComponent(
																												Checkbox_serv16))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								jPanel1Layout
																										.createSequentialGroup()
																										.addContainerGap()
																										.addComponent(
																												Textfiled_serv16,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												30,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				Slider_serv16,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				89,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(0,
																				0,
																				Short.MAX_VALUE)))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								Textfiled_serv5,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								30,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								Checkbox_serv5))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				Slider_serv5,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				89,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								Checkbox_serv7)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(21,
																												21,
																												21)
																										.addComponent(
																												Textfiled_serv7,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												30,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				Slider_serv7,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				89,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(166, Short.MAX_VALUE))
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(234,
																												234,
																												234)
																										.addComponent(
																												Textfiled_serv14,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												30,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								jPanel1Layout
																										.createSequentialGroup()
																										.addContainerGap()
																										.addComponent(
																												Checkbox_serv14)))
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				Slider_serv14,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				89,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								Checkbox_serv15,
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								Textfiled_serv15,
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								30,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				Slider_serv15,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				89,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				Checkbox_serv17))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(0,
																				0,
																				Short.MAX_VALUE)
																		.addComponent(
																				Textfiled_serv17,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				30,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												Slider_serv17,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												89,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(152, 152, 152))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				Textfiled_serv1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				30,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(17,
																				17,
																				17))
														.addComponent(
																Checkbox_serv1,
																javax.swing.GroupLayout.Alignment.TRAILING))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												Slider_serv1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												89,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(475, 475, 475)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(34, 34, 34)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(
																				Slider_serv5,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				43,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												Checkbox_serv5,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												15,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												Textfiled_serv5,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addComponent(
																								Slider_serv3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								43,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																		.addGroup(
																				jPanel1Layout
																						.createSequentialGroup()
																						.addComponent(
																								Slider_serv1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								43,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								Checkbox_serv3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								15,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																						.addComponent(
																								Textfiled_serv3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(
																				jPanel1Layout
																						.createSequentialGroup()
																						.addComponent(
																								Checkbox_serv1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								15,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																						.addComponent(
																								Textfiled_serv1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGap(7,
																								7,
																								7)
																						.addGroup(
																								jPanel1Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(
																												Slider_serv2,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												43,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGroup(
																												jPanel1Layout
																														.createSequentialGroup()
																														.addComponent(
																																Checkbox_serv2,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																15,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addGap(7,
																																7,
																																7)
																														.addComponent(
																																Textfiled_serv2,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																javax.swing.GroupLayout.PREFERRED_SIZE))
																										.addGroup(
																												jPanel1Layout
																														.createSequentialGroup()
																														.addComponent(
																																Checkbox_serv4,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																15,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addGap(7,
																																7,
																																7)
																														.addComponent(
																																Textfiled_serv4,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																javax.swing.GroupLayout.PREFERRED_SIZE))
																										.addComponent(
																												Slider_serv4,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												43,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGap(1,
																								1,
																								1))))
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(39,
																				39,
																				39)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING)
																														.addGroup(
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				Checkbox_serv6,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				15,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addGap(6,
																																				6,
																																				6)
																																		.addComponent(
																																				Textfiled_serv7,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))
																														.addComponent(
																																Slider_serv6,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																43,
																																javax.swing.GroupLayout.PREFERRED_SIZE))
																										.addGap(17,
																												17,
																												17)
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addGroup(
																																jPanel1Layout
																																		.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING,
																																				false)
																																		.addComponent(
																																				Slider_serv8,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				43,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addGroup(
																																				jPanel1Layout
																																						.createSequentialGroup()
																																						.addComponent(
																																								Checkbox_serv8,
																																								javax.swing.GroupLayout.PREFERRED_SIZE,
																																								15,
																																								javax.swing.GroupLayout.PREFERRED_SIZE)
																																						.addPreferredGap(
																																								javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																								Short.MAX_VALUE)
																																						.addComponent(
																																								Textfiled_serv8,
																																								javax.swing.GroupLayout.PREFERRED_SIZE,
																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																								javax.swing.GroupLayout.PREFERRED_SIZE)))
																														.addGroup(
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				Checkbox_serv9,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				15,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																		.addComponent(
																																				Textfiled_serv9,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												Slider_serv9,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												43,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(1,
																												1,
																												1))))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(37,
																				37,
																				37)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								Slider_serv7,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								43,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												Checkbox_serv7,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												15,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												Textfiled_serv6,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))))
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(43,
																				43,
																				43)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																						.addComponent(
																								Slider_serv10,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								43,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												Checkbox_serv10,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												15,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												Textfiled_serv10,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE))))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(34,
																				34,
																				34)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												Checkbox_serv11,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												15,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												Textfiled_serv11,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addComponent(
																								Slider_serv11,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								43,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				Checkbox_serv12,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				15,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				Textfiled_serv12,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(
																Slider_serv12,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																43,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																		.addGroup(
																				jPanel1Layout
																						.createSequentialGroup()
																						.addComponent(
																								Checkbox_serv13,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								15,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								Textfiled_serv13,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addComponent(
																				Slider_serv13,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				43,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(38,
																												38,
																												38)
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																Slider_serv14,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																43,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addGroup(
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				Checkbox_serv14,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				15,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addGap(7,
																																				7,
																																				7)
																																		.addComponent(
																																				Textfiled_serv14,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(46,
																												46,
																												46)
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																Slider_serv15,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																43,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addGroup(
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				Checkbox_serv15,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				15,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				Textfiled_serv15,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)))))
																		.addContainerGap(
																				98,
																				Short.MAX_VALUE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												Checkbox_serv17,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												15,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												Textfiled_serv17,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								jPanel1Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING)
																										.addComponent(
																												Slider_serv17,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												43,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																false)
																														.addGroup(
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				Checkbox_serv16,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				15,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				Short.MAX_VALUE)
																																		.addComponent(
																																				Textfiled_serv16,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))
																														.addComponent(
																																Slider_serv16,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																43,
																																javax.swing.GroupLayout.PREFERRED_SIZE))))
																		.addGap(62,
																				62,
																				62)))));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(115, 115, 115)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addComponent(
																																		Lable_port)
																																.addGap(31,
																																		31,
																																		31)
																																.addComponent(
																																		Comobox_port,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		83,
																																		javax.swing.GroupLayout.PREFERRED_SIZE))
																												.addGroup(
																														layout.createSequentialGroup()
																																.addComponent(
																																		Lable_baudrate)
																																.addGap(31,
																																		31,
																																		31)
																																.addComponent(
																																		Comobox_boudrate,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		83,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)))
																								.addGroup(
																										layout.createSequentialGroup()
																												.addComponent(
																														Lable_databits)
																												.addGap(31,
																														31,
																														31)
																												.addComponent(
																														Comobox_datebits,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														83,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGroup(
																										layout.createSequentialGroup()
																												.addComponent(
																														Lable_stopbits)
																												.addGap(31,
																														31,
																														31)
																												.addComponent(
																														Comobox_stopbits,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														83,
																														javax.swing.GroupLayout.PREFERRED_SIZE)))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										Lable_paritybits)
																								.addGap(31,
																										31,
																										31)
																								.addComponent(
																										Comobox_paritybits,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										83,
																										javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addContainerGap(
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																				.addComponent(
																						Button_send,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						Button_openport,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		Button_closeport)
																.addGap(18, 18,
																		18)))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(64, 64, 64)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(Lable_port)
												.addComponent(
														Comobox_port,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(27, 27, 27)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(Lable_baudrate)
												.addComponent(
														Comobox_boudrate,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(31, 31, 31)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(Lable_databits)
												.addComponent(
														Comobox_datebits,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(33, 33, 33)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(Lable_stopbits)
												.addComponent(
														Comobox_stopbits,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(34, 34, 34)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(Lable_paritybits)
												.addComponent(
														Comobox_paritybits,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(37, 37, 37)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(Button_openport)
												.addComponent(Button_closeport))
								.addGap(30, 30, 30)
								.addComponent(Button_send)
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(36, Short.MAX_VALUE)
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));

		pack();

	}// </editor-fold>
	
	/*
	 * this part is created by netbeans for the frame automately, pls do not change
	 * end
	 */
	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	public void setSlidervalue1(String ss) {
		mesg1 = ss;
	}

	public String getSlidervalue1() {
		return mesg1;
	}

	public void setSlidervalue2(String ss) {
		mesg2 = ss;
	}

	public String getSlidervalue2() {
		return mesg2;
	}

	public void setSlidervalue3(String ss) {
		mesg3 = ss;
	}

	public String getSlidervalue3() {
		return mesg3;
	}

	public void setSlidervalue4(String ss) {
		mesg4 = ss;
	}

	public String getSlidervalue4() {
		return mesg4;
	}

	public void setSlidervalue5(String ss) {
		mesg5 = ss;
	}

	public String getSlidervalue5() {
		return mesg5;
	}

	public void setSlidervalue6(String ss) {
		mesg6 = ss;
	}

	public String getSlidervalue6() {
		return mesg6;
	}

	public void setSlidervalue7(String ss) {
		mesg7 = ss;
	}

	public String getSlidervalue7() {
		return mesg7;
	}

	public void setSlidervalue8(String ss) {
		mesg8 = ss;
	}

	public String getSlidervalue8() {
		return mesg8;
	}

	public void setSlidervalue9(String ss) {
		mesg9 = ss;
	}

	public String getSlidervalue9() {
		return mesg9;
	}

	public void setSlidervalue10(String ss) {
		mesg10 = ss;
	}

	public String getSlidervalue10() {
		return mesg10;
	}

	public void setSlidervalue11(String ss) {
		mesg11 = ss;
	}

	public String getSlidervalue11() {
		return mesg11;
	}

	public void setSlidervalue12(String ss) {
		mesg12 = ss;
	}

	public String getSlidervalue12() {
		return mesg12;
	}

	public void setSlidervalue13(String ss) {
		mesg13 = ss;
	}

	public String getSlidervalue13() {
		return mesg13;
	}

	public void setSlidervalue14(String ss) {
		mesg14 = ss;
	}

	public String getSlidervalue14() {
		return mesg14;
	}

	public void setSlidervalue15(String ss) {
		mesg15 = ss;
	}

	public String getSlidervalue15() {
		return mesg15;
	}

	public void setSlidervalue16(String ss) {
		mesg16 = ss;
	}

	public String getSlidervalue16() {
		return mesg16;
	}

	public void setSlidervalue17(String ss) {
		mesg17 = ss;
	}

	public String getSlidervalue17() {
		return mesg17;
	}

	public void getMesgFromTextfield() {
		setSlidervalue1(Textfiled_serv1.getText());
		setSlidervalue2(Textfiled_serv2.getText());
		setSlidervalue3(Textfiled_serv3.getText());
		setSlidervalue4(Textfiled_serv4.getText());
		setSlidervalue5(Textfiled_serv5.getText());
		setSlidervalue6(Textfiled_serv6.getText());
		setSlidervalue7(Textfiled_serv7.getText());
		setSlidervalue8(Textfiled_serv8.getText());
		setSlidervalue9(Textfiled_serv9.getText());
		setSlidervalue10(Textfiled_serv10.getText());
		setSlidervalue11(Textfiled_serv11.getText());
		setSlidervalue12(Textfiled_serv12.getText());
		setSlidervalue13(Textfiled_serv13.getText());
		setSlidervalue14(Textfiled_serv14.getText());
		setSlidervalue15(Textfiled_serv15.getText());
		setSlidervalue16(Textfiled_serv16.getText());
		setSlidervalue17(Textfiled_serv17.getText());
	}

	public void actionPerformed(ActionEvent e) {
		if (e.getSource() == Comobox_port || e.getSource() == Comobox_boudrate
				|| e.getSource() == Comobox_datebits
				|| e.getSource() == Comobox_stopbits
				|| e.getSource() == Comobox_paritybits) {
			// statusLb.setText(serial.initStatus());
		}
		if (e.getSource() == Button_openport) {
			setComponentsEnabled(false);
			setInitSerial();
			serial.openSerialPort();
		}
		if (e.getSource() == Button_closeport) {
			if (serial.isSerialPort()) {
				serial.closeSerialPort();
			}
			setComponentsEnabled(true);
		}

		if (e.getSource() == Button_send) {
			if (!serial.isSerialPort()) {
				showErrMesgbox("请先打开串行端口!");
				return;
			}
			StringBuilder temp = new StringBuilder();
			getMesgFromTextfield();
			temp = dealmesg.appendMessage(mesg1, mesg2, mesg3, mesg4, mesg5,
					mesg6, mesg7, mesg8, mesg9, mesg10, mesg11, mesg12, mesg13,
					mesg14, mesg15, mesg16, mesg17);
			System.out.println("temp: " + temp);
			serial.sendDataToSeriaPort(temp.toString());

		}
	}

	public void setSlider(JSlider slider, ChangeListener listener,
			final JTextField textfield) {

		// 设置绘制刻度
		slider.setPaintTicks(true);
		// 设置主、次刻度的间距
		slider.setMajorTickSpacing(20);
		slider.setMinorTickSpacing(5);
		// 设置绘制刻度标签，默认绘制数值刻度标签
		slider.setPaintLabels(true);
		listener = new ChangeListener() {
			@Override
			public void stateChanged(ChangeEvent event) {
				// TODO Auto-generated method stub
				// 取出滑动条的值，并在文本中显示出来
				JSlider source = (JSlider) event.getSource();
				String ss;
				ss = Integer.toString(source.getValue());
				// setSlidervalue1(ss);
				System.out.println("serv: " + ss);
				textfield.setText(ss);

			}
		};

		slider.addChangeListener(listener);

		// box.add(new JLabel(description + "："));

	}

	public String getPortName() {
		return Comobox_port.getSelectedItem().toString();
	}

	public String getrate() {
		return Comobox_boudrate.getSelectedItem().toString();
	}

	public String getdata() {
		return Comobox_datebits.getSelectedItem().toString();
	}

	public String getstop() {
		// return stopCombox.getSelectedItem().toString();
		return Integer.toString(Comobox_stopbits.getSelectedIndex() + 1);
	}

	public String getparity() {
		return Integer.toString(Comobox_paritybits.getSelectedIndex());
	}

	public void setInitSerial() {
		serial.setportname(getPortName());
		serial.setdata(getdata());
		// serial.setportname(ss);
		serial.setrate(getrate());
		serial.setstop(getstop());
		serial.setparity(getparity());
	}

	public void setComponentsEnabled(boolean enabled) {
		Button_openport.setEnabled(enabled);
		// Button_closeport.setEnabled(enabled);
		Comobox_port.setEnabled(enabled);
		Comobox_boudrate.setEnabled(enabled);
		Comobox_datebits.setEnabled(enabled);
		Comobox_stopbits.setEnabled(enabled);
		Comobox_paritybits.setEnabled(enabled);
	}

	public void showErrMesgbox(String msg) {
		JOptionPane.showMessageDialog(this, msg);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(M.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(M.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(M.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(M.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new M();
			}
		});
	}

}
